apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydrogendeploy
  labels:
    app: hydrogendeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydrogendeploy
  template:
    metadata:
      labels:
        app: hydrogendeploy
    spec:
      containers:
        - name: hydrogencontainer
          image: 640315517146.dkr.ecr.us-east-2.amazonaws.com/hydrogencontainer:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
